a = float(input("nhap so a bat ky: "))
b = float(input("nhap so b bat ky: "))
print("a + b ",a+b)
print("a - b ",a-b)
print("a * b ",a*b)
print("a // b ",a//b)
print("a**b ",a**b)
print("a % b ",a%b)
if a > b:
    print("a > b")
elif a < b:
    print("a < b")
else: print("a = b")
print("a AND b ",a and b)
print("a OR b ",a or b)
print("a XOR b ",int(a) ^ int(b))
print("NOT a == b ",~int(a)==int(b))
print(int(a)>>1)
print(int(a)<<1)
